export interface FunctionEntry {
    description?: string,
    documentationLink?: string,
    signature?: string
    parameters?: {
        label: string,
        type?: string,
        documentation?: string
    }[]
    returns?: string,
    detail?: string,
    deprecated?: boolean
}

type globalVariablesList = { [name: string]: {
    description?: string,
    deprecated?: boolean
}}

export const globalFunctions: { [name: string]: FunctionEntry} = {
    abs:
    {
        description:
        `Returns the absolute value of the input number.`,

        documentationLink: "Maths_And_Numbers/Number_Functions/abs",

        parameters: [
            { label: 'val', type: "number", documentation: "number" }
        ],
        returns: "number",
        signature: '(val)'
    },
    draw_sprite: {
        description:
        `Draws the given sprite and sub-image at a position within the game room.`,

        documentationLink: "Drawing/Sprites_And_Tiles/draw_sprite",

        parameters: [
            { label: 'sprite', type: "SpriteAsset", documentation: "" },
            { label: 'subimg', type: "number", documentation: "" },
            { label: 'x', type: "number", documentation: "" },
            { label: 'y', type: "number", documentation: "" }
        ],
        signature: "(sprite, subimg, x, y)"
    }
},
globalVariables: globalVariablesList = {
    async_load: {description: ""},
    browser_height: {description: ""},
    browser_width: {description: ""},
    caption_health: {description: ""},
    caption_lives: {description: ""},
    caption_score: {description: ""},
    current_day: {description: ""},
    current_hour: {description: ""},
    current_minute: {description: ""},
    current_month: {description: ""},
    current_second: {description: ""},
    current_time: {description: ""},
    current_weekday: {description: ""},
    current_year: {description: ""},
    cursor_sprite: {description: ""},
    debug_mode: {description: ""},
    delta_time: {description: ""},
    display_aa: {description: ""},
    error_last: {description: ""},
    error_occurred: {description: ""},
    event_action: {description: ""},
    event_number: {description: ""},
    event_object: {description: ""},
    event_type: {description: ""},
    fps: {description: ""},
    fps_real: {description: ""},
    game_id: {description: ""},
    health: {description: ""},
    instance_count: {description: ""},
    instance_id: {description: ""},
    keyboard_key: {description: ""},
    keyboard_lastchar: {description: ""},
    keyboard_lastkey: {description: ""},
    keyboard_string: {description: ""},
    lives: {description: ""},
    mouse_button: {description: ""},
    mouse_lastbutton: {description: ""},
    mouse_x: {description: ""},
    mouse_y: {description: ""},
    os_browser: {description: ""},
    os_device: {description: ""},
    os_type: {description: ""},
    os_version: {description: ""},
    program_directory: {description: ""},
    room: {description: ""},
    room_caption: {description: ""},
    room_first: {description: ""},
    room_height: {description: ""},
    room_last: {description: ""},
    room_persistent: {description: ""},
    room_speed: {description: ""},
    room_width: {description: ""},
    score: {description: ""},
    show_health: {description: ""},
    show_lives: {description: ""},
    show_score: {description: ""},
    temp_directory: {description: ""},
    transition_color: {description: ""},
    transition_kind: {description: ""},
    transition_steps: {description: ""},
    webgl_enabled: {description: ""},
    working_directory: {description: ""},
    alarm: {description: ""},
    bbox_bottom: {description: ""},
    bbox_left: {description: ""},
    bbox_right: {description: ""},
    bbox_top: {description: ""},
    depth: {description: ""},
    direction: {description: ""},
    friction: {description: ""},
    gravity: {description: ""},
    gravity_direction: {description: ""},
    hspeed: {description: ""},
    id: {description: ""},
    image_alpha: {description: ""},
    image_angle: {description: ""},
    image_blend: {description: ""},
    image_index: {description: ""},
    image_number: {description: ""},
    image_single: {description: ""},
    image_speed: {description: ""},
    image_xscale: {description: ""},
    image_yscale: {description: ""},
    mask_index: {description: ""},
    object_index: {description: ""},
    path_endaction: {description: ""},
    path_index: {description: ""},
    path_orientation: {description: ""},
    path_position: {description: ""},
    path_positionprevious: {description: ""},
    path_scale: {description: ""},
    path_speed: {description: ""},
    persistent: {description: ""},
    phy_active: {description: ""},
    phy_angular_damping: {description: ""},
    phy_angular_velocity: {description: ""},
    phy_bullet: {description: ""},
    phy_collision_points: {description: ""},
    phy_collision_x: {description: ""},
    phy_collision_y: {description: ""},
    phy_col_normal_x: {description: ""},
    phy_col_normal_y: {description: ""},
    phy_com_x: {description: ""},
    phy_com_y: {description: ""},
    phy_dynamic: {description: ""},
    phy_fixed_rotation: {description: ""},
    phy_inertia: {description: ""},
    phy_kinematic: {description: ""},
    phy_linear_damping: {description: ""},
    phy_linear_velocity_x: {description: ""},
    phy_linear_velocity_y: {description: ""},
    phy_mass: {description: ""},
    phy_position_x: {description: ""},
    phy_position_xprevious: {description: ""},
    phy_position_y: {description: ""},
    phy_position_yprevious: {description: ""},
    phy_rotation: {description: ""},
    phy_sleeping: {description: ""},
    phy_speed: {description: ""},
    phy_speed_x: {description: ""},
    phy_speed_y: {description: ""},
    solid: {description: ""},
    speed: {description: ""},
    sprite_height: {description: ""},
    sprite_index: {description: ""},
    sprite_width: {description: ""},
    sprite_xoffset: {description: ""},
    sprite_yoffset: {description: ""},
    timeline_index: {description: ""},
    timeline_loop: {description: ""},
    timeline_position: {description: ""},
    timeline_running: {description: ""},
    timeline_speed: {description: ""},
    visible: {description: ""},
    vspeed: {description: ""},
    x: {description: ""},
    xprevious: {description: ""},
    xstart: {description: ""},
    y: {description: ""},
    yprevious: {description: ""},
    ystart: {description: ""},
    view_enabled: {description: ""},
    view_current: {description: ""},
    background_color: {description: ""},
    background_showcolor: {description: ""},
    background_visible: {description: ""},
    background_foreground: {description: ""},
    background_index: {description: ""},
    background_x: {description: ""},
    background_y: {description: ""},
    background_width: {description: ""},
    background_height: {description: ""},
    background_htiled: {description: ""},
    background_vtiled: {description: ""},
    background_xscale: {description: ""},
    background_yscale: {description: ""},
    background_hspeed: {description: ""},
    background_vspeed: {description: ""},
    background_blend: {description: ""},
    background_alpha: {description: ""},
    layer: {description: ""},
    view_camera: {description: ""},
    event_data: {description: ""},

    //Obsolete variables
    view_angle: {description: "", deprecated: true},
    view_hborder: {description: "", deprecated: true},
    view_hport: {description: "", deprecated: true},
    view_hspeed: {description: "", deprecated: true},
    view_hview: {description: "", deprecated: true},
    view_object: {description: "", deprecated: true},
    view_vborder: {description: "", deprecated: true},
    view_visible: {description: "", deprecated: true},
    view_vspeed: {description: "", deprecated: true},
    view_wport: {description: "", deprecated: true},
    view_wview: {description: "", deprecated: true},
    view_xport: {description: "", deprecated: true},
    view_xview: {description: "", deprecated: true},
    view_yport: {description: "", deprecated: true},
    view_yview: {description: "", deprecated: true},
},
constants = {
    _GMLINE_: {},
    _GMFILE_: {},
    _GMFUNCTION_: {},
    debug_mode: {},
},
keywords = {
    argument: {},
    argument_count: {},
    argument_relative: {},
    self: {},
    other: {},
    global: {},
    try: {},
    catch: {},
    finally: {},
    delete: {},
    and: {},
    break: {},
    case: {},
    continue: {},
    default: {},
    do: {},
    else: {},
    exit: {},
    for: {},
    if: {},
    not: {},
    or: {},
    repeat: {},
    return: {},
    switch: {},
    until: {},
    var: {},
    while: {},
    with: {},
    xor: {}
};
